### ISSUE TITLE
Wrong [Estimated time left] of a normal withdrawal

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/light-godwoken#168] opened 2022-07-22 15:17 UTC
![image](https://user-images.githubusercontent.com/1297478/180470412-eeef3fc0-ed64-4435-8361-0e29995be337.png)

[Estimated time left] should be about 7 days

**Comment by ShookLyngs** [comment] 2022-07-25 09:46
The bug is caused by the wrong time display format. Originally we didn't think we were going to change the block_finality to 7 days, so the estimated time left is only displayed up to "minutes".

The issue should be fixed in this PR:
- https://github.com/nervosnetwork/light-godwoken/pull/169

**Closed** 2022-07-26 08:02 UTC
Labels: bug
